@startuml(id=Components)
scale max 2000x1409
title Platforma bankowości online - API - Components
caption Diagram komponentów aplikacji API

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  rectangleFontColor #ffffff
  rectangleStereotypeFontColor #ffffff
}
rectangle 9 <<Container>> #bbbbbb [
  Aplikacja mobilna
  --
  Dostarcza ograniczoną
  funkcjonalność bankowości
  online dla klientów
]
database 11 <<Container>> #1168bd [
  Baza danych
  --
  Informacje o klientach,
  hashowane hasła, logi etc
]
rectangle 4 <<Software System>> #1168bd [
  E-mail System
  --
  System e-mailowy Microsoft
  Exchange
]
rectangle 3 <<Software System>> #1168bd [
  System bankowy Mainframe
  --
  Core'owy system bankowy.
  Zawiera informacje o
  klientach, transakcjach,
  kontach, etc.
]
package "API" <<Container>> {
  component 22 <<Komponent: Spring Bean>> #dddddd [
    Fasada do Mainframe Banking System
    --
    Fasada do mainframe banking
    system
  ]
  component 21 <<Komponent: Spring Bean>> #dddddd [
    Komponent E-mail
    --
    Pozwala na wysyłanie e-maili
  ]
  component 20 <<Komponent: Spring Bean>> #dddddd [
    Komponent bezpieczeństwa
    --
    Dostarcza funkcjonalność
    potrzebną do zmian hasła
  ]
  component 18 <<Komponent: Spring MVC Rest Controller>> #dddddd [
    Konta bankowe
    --
    Pozwala na wgląd w widok
    posiadanych kont
  ]
  component 17 <<Komponent: Spring MVC Rest Controller>> #dddddd [
    Logowanie
    --
    Pozwala na logowanie do
    platformy bankowej
  ]
  component 19 <<Komponent: Spring MVC Rest Controller>> #dddddd [
    Resetowanie hasła
    --
    Pozwala na wygenerowanie URL
    do resetu hasła
  ]
}
9 .[#707070].> 18 : <<JSON/HTTPS>>\nUżywa
9 .[#707070].> 17 : <<JSON/HTTPS>>\nUżywa
9 .[#707070].> 19 : <<JSON/HTTPS>>\nUżywa
22 .[#707070].> 3 : <<XML/HTTPS>>\nUżywa
21 .[#707070].> 4 : <<XML/HTTPS>>\nUżywa
20 .[#707070].> 11 : <<JDBC>>\nCzyta i zapisuje do
18 .[#707070].> 22 : <<SYNC>>\nUżywa
17 .[#707070].> 20 : <<SYNC>>\nUżywa
19 .[#707070].> 21 : <<SYNC>>\nUżywa
19 .[#707070].> 20 : <<SYNC>>\nUżywa
@enduml
